const {app,BrowserWindow,ipcMain,screen,session,Menu,Tray,nativeImage,shell}=require('electron');const path=require('node:path');const fs=require('node:fs');const {Monitor}=require('./monitor.cjs');const {loadSettings,saveSettings,layouts,chooseDisplay}=require('./settings.cjs');
let win,tray,monitor,grokWindow,settings,file,grokTimer,quitting=false;
if(!app.requestSingleInstanceLock())app.quit();
app.on('second-instance',()=>{win?.show();win?.focus();});
function placeWindow(){if(!win)return;const d=chooseDisplay(screen.getAllDisplays(),screen.getPrimaryDisplay().id,settings.displayId);win.setFullScreen(false);win.setBounds(d.bounds);win.setFullScreen(true);settings.displayId=d.id;saveSettings(file,settings);}
function trusted(event){return win && event.sender===win.webContents && event.senderFrame?.url===win.webContents.getURL();}
function handle(name,fn){ipcMain.handle(name,(event,...args)=>{if(!trusted(event))throw new Error('Untrusted sender');return fn(...args);});}
async function pollGrok(){try{const s=session.fromPartition('persist:grok');const cookies=await s.cookies.get({url:'https://grok.com'});if(!cookies.some(c=>/^(sso|sso-rw)$/.test(c.name)))return monitor.setGrok({vendor:'Grok',status:'auth',message:'Connect Grok',windows:[]});
 const response=await s.fetch('https://grok.com/rest/rate-limits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestKind:'DEFAULT',modelName:'grok-4-auto'}),signal:AbortSignal.timeout(15000)});
 if(!response.ok)return monitor.setGrok({vendor:'Grok',status:response.status===401?'auth':'unavailable',message:`Grok HTTP ${response.status} · open connection`,windows:[]});
 const r=await response.json();const limit=Number(r.totalRequests),remaining=Number(r.remainingQueries??r.remainingRequests);const duration=Number(r.windowSizeSeconds);const reset=r.resetTime?Date.parse(r.resetTime):r.resetAt?Number(r.resetAt)*1000:null;
 if(!Number.isFinite(limit)||limit<=0||!Number.isFinite(remaining))return monitor.setGrok({vendor:'Grok',status:'unavailable',message:'Website quota format changed',windows:[]});
 monitor.setGrok({vendor:'Grok',status:'live',sampledAt:Date.now(),windows:[{label:`Grok auto${duration?' · '+duration/3600+'h':''}`,used:100*(limit-remaining)/limit,resetAt:reset}],message:reset?null:'Website does not report a reset time'});
 }catch{monitor.setGrok({vendor:'Grok',status:'unavailable',message:'Open Grok connection to sign in',windows:[]});}}
function connectGrok(){if(grokWindow){grokWindow.show();return;}grokWindow=new BrowserWindow({width:1100,height:800,title:'Connect Grok — SysMon',webPreferences:{partition:'persist:grok',nodeIntegration:false,contextIsolation:true,sandbox:true}});grokWindow.webContents.setWindowOpenHandler(()=>({action:'deny'}));grokWindow.webContents.on('will-navigate',(event,url)=>{try{if(!['grok.com','accounts.x.ai','auth.x.ai','x.com','twitter.com'].includes(new URL(url).hostname))event.preventDefault();}catch{event.preventDefault();}});grokWindow.loadURL('https://grok.com');grokWindow.on('closed',()=>{grokWindow=null;pollGrok();});}
app.whenReady().then(()=>{
 file=path.join(app.getPath('userData'),'settings.json');settings=loadSettings(file);monitor=new Monitor();
 Menu.setApplicationMenu(null);win=new BrowserWindow({show:false,frame:false,backgroundColor:'#0a0d0b',webPreferences:{preload:path.join(__dirname,'preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true}});
 win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());win.webContents.on('before-input-event',(e,input)=>{if(input.type==='keyDown'&&input.key==='Escape'){win.setFullScreen(false);}if(input.type==='keyDown'&&input.key==='F11'){win.setFullScreen(!win.isFullScreen());}});
 handle('snapshot',()=>monitor.state);handle('settings',()=>settings);handle('layout',layout=>{if(!layouts.includes(layout))throw new Error('Invalid layout');settings.layout=layout;saveSettings(file,settings);return settings;});handle('connect-grok',()=>connectGrok());handle('open-ci',url=>{if(typeof url==='string'&&/^https:\/\/github\.com\/[^/]+\/[^/]+\/pull\/\d+$/.test(url))return shell.openExternal(url);});
 monitor.on('update',s=>{if(!win.isDestroyed())win.webContents.send('update',s);});win.loadFile(path.join(__dirname,'renderer/index.html'));win.once('ready-to-show',()=>{placeWindow();win.show();});
 const icon=nativeImage.createFromDataURL('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABGElEQVQ4T6WTwQ3CMAxF/0xgB8AAmIAJMAEmYAImwARsgAkwAROwAWwAjEAH4BkHJIpDUuoBkSxn8X/fjgPgKwkIJD3Pd0KIIZM9SZA0A3CH+AEoqQNwBTDT3CSAfYG6qXMF1fmsPF8awDnASERpwJsCGNUteDWAsgATGaBLsjZWGPHMpPWg6X+CJAFo64Qlaz2lrZ+A/PpTk+ZqXAHcAGxuIOOu1SVPvsm89MPMmqMwAHZwnwNUbi99/f4HsCtOgdKaBFRmi0EjXDkUPSpByQuBQCVJeBxIGcqhAGVpMoMssoB8KTIJPBGEDqwLD+nDTngXofIdcaDpSCNsZKUCRmvauvcBV4KNhgUdCI93EF+/IPTVHX3+8WcNVa6XD/WG0evAKI1LGNRDgvBAAAAAElFTkSuQmCC');
 tray=new Tray(icon);tray.setToolTip('SysMon');const menu=()=>Menu.buildFromTemplate([{label:'Show on second display',click:()=>{settings.displayId=null;placeWindow();win.show();}},{label:'Displays',submenu:screen.getAllDisplays().map((d,i)=>({label:`Display ${i+1} · ${d.size.width} × ${d.size.height}`,type:'radio',checked:d.id===settings.displayId,click:()=>{settings.displayId=d.id;placeWindow();win.show();}}))},{label:'Connect Grok',click:connectGrok},{label:'Start at login',type:'checkbox',checked:app.getLoginItemSettings().openAtLogin,click:item=>app.setLoginItemSettings({openAtLogin:item.checked})},{type:'separator'},{label:'Quit SysMon',click:()=>{quitting=true;app.quit();}}]);tray.on('click',()=>win.show());tray.on('right-click',()=>tray.popUpContextMenu(menu()));
 win.on('close',e=>{if(!quitting){e.preventDefault();win.hide();}});screen.on('display-added',placeWindow);screen.on('display-removed',placeWindow);
 if(app.isPackaged && process.platform!=='linux')app.setLoginItemSettings({openAtLogin:true});
 if(app.isPackaged&&process.platform==='linux'){const dir=path.join(app.getPath('home'),'.config/autostart');fs.mkdirSync(dir,{recursive:true});const exe=process.env.APPIMAGE||process.execPath;fs.writeFileSync(path.join(dir,'sysmon.desktop'),`[Desktop Entry]\nType=Application\nName=SysMon\nExec="${exe.replaceAll('"','\\"')}"\nX-GNOME-Autostart-enabled=true\n`);}
 monitor.start();pollGrok();grokTimer=setInterval(pollGrok,120000);
});
app.on('before-quit',()=>{quitting=true;monitor?.stop();clearInterval(grokTimer);});app.on('window-all-closed',()=>{});
